"""Port of packages/ocr/src/normalize.ts.

The app runs that normalizer over whatever the model emits. If training labels
are not already in its output form, the model learns a dialect the app then
rewrites at inference time, and every rewrite is a chance to change meaning. So
labels are pushed through the same transformation before training.

This is a line-by-line port, not a reimplementation. tests/test_normalize.py
checks it against golden output generated by the TypeScript original
(tests/gen_golden.mts), so a change on either side shows up as a failure.

Known divergences from the TypeScript, both harmless for LaTeX labels:
  - JS `\\s` matches U+FEFF, Python's does not.
  - JS `String.trim()` and Python `str.strip()` disagree on a few exotic
    Unicode space characters.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field

# re.sub expands backslash escapes in a replacement *template*, so "\\times"
# would become a tab plus "imes". Every replacement here is passed as a lambda
# to bypass template processing entirely.
UNICODE: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"[\u00d7\u2715\u2716]"), "\\times "),
    (re.compile(r"[\u00f7]"), "\\div "),
    (re.compile(r"[\u00b7\u2022\u2219\u22c5]"), "\\cdot "),
    (re.compile(r"[\u2212\u2013\u2014\u2015]"), "-"),
    (re.compile(r"[\u2044\u2215]"), "/"),
    (re.compile(r"\u221a"), "\\sqrt"),
    (re.compile(r"\u221b"), "\\sqrt[3]"),
    (re.compile(r"\u2264"), "\\le "),
    (re.compile(r"\u2265"), "\\ge "),
    (re.compile(r"\u2260"), "\\neq "),
    (re.compile(r"\u00b1"), "\\pm "),
    (re.compile(r"\u221e"), "\\infty "),
    (re.compile(r"[\u2018\u2019\u02bc]"), "'"),
    (re.compile(r"[\u201c\u201d]"), '"'),
    (re.compile(r"\u00a0"), " "),
]

GREEK: dict[str, str] = {
    "\u03b1": "\\alpha ", "\u03b2": "\\beta ", "\u03b3": "\\gamma ", "\u03b4": "\\delta ",
    "\u03b5": "\\epsilon ", "\u03b8": "\\theta ", "\u03bb": "\\lambda ", "\u03bc": "\\mu ",
    "\u03c0": "\\pi ", "\u03c1": "\\rho ", "\u03c3": "\\sigma ", "\u03c4": "\\tau ",
    "\u03c6": "\\phi ", "\u03c9": "\\omega ",
}

SUPERSCRIPTS: dict[str, str] = {
    "\u2070": "0", "\u00b9": "1", "\u00b2": "2", "\u00b3": "3", "\u2074": "4",
    "\u2075": "5", "\u2076": "6", "\u2077": "7", "\u2078": "8", "\u2079": "9",
    "\u207a": "+", "\u207b": "-",
}

VULGAR: dict[str, str] = {
    "\u00bd": "\\frac{1}{2}", "\u2153": "\\frac{1}{3}", "\u2154": "\\frac{2}{3}",
    "\u00bc": "\\frac{1}{4}", "\u00be": "\\frac{3}{4}", "\u2155": "\\frac{1}{5}",
    "\u2159": "\\frac{1}{6}", "\u215b": "\\frac{1}{8}",
}

NOISE_COMMANDS = [
    "displaystyle", "textstyle", "scriptstyle", "scriptscriptstyle",
    "limits", "nolimits", "thinspace", "medspace", "thickspace",
    "negthinspace", "quad", "qquad", "bigl", "bigr", "Bigl", "Bigr",
    "biggl", "biggr", "Biggl", "Biggr", "big", "Big", "bigg", "Bigg",
]

TRANSPARENT_WRAPPERS = [
    "mathrm", "mathit", "mathbf", "mathsf", "mathtt", "mathnormal",
    "operatorname", "text", "textrm", "textit", "mbox", "boldsymbol",
]

_SUPERSCRIPT_RUN = re.compile(r"[\u2070\u00b9\u00b2\u00b3\u2074-\u2079\u207a\u207b]+")


@dataclass
class NormalizeReport:
    latex: str
    notes: list[str] = field(default_factory=list)


def _sub(pattern: re.Pattern[str] | str, replacement: str, s: str) -> str:
    return re.sub(pattern, lambda _m: replacement, s)


def _strip_delimiters(s: str, notes: list[str]) -> str:
    out = s.strip()
    before = out
    out = _sub(r"^\$\$?", "", out)
    out = _sub(r"\$\$?$", "", out)
    out = _sub(r"^\\\(", "", out)
    out = _sub(r"\\\)$", "", out)
    out = _sub(r"^\\\[", "", out)
    out = _sub(r"\\\]$", "", out)
    if out != before:
        notes.append("removed math delimiters")
    return out.strip()


def _replace_unicode(s: str, notes: list[str]) -> str:
    out = s
    before = out
    for pattern, replacement in UNICODE:
        out = _sub(pattern, replacement, out)
    for ch, replacement in GREEK.items():
        out = out.replace(ch, replacement)
    for ch, replacement in VULGAR.items():
        out = out.replace(ch, replacement)

    def _run(match: re.Match[str]) -> str:
        digits = "".join(SUPERSCRIPTS.get(c, "") for c in match.group(0))
        return f"^{{{digits}}}" if digits else ""

    out = _SUPERSCRIPT_RUN.sub(_run, out)

    if out != before:
        notes.append("converted Unicode symbols to LaTeX")
    return out


def _strip_noise(s: str, notes: list[str]) -> str:
    out = s
    before = out
    for cmd in NOISE_COMMANDS:
        out = _sub(rf"\\{cmd}(?![a-zA-Z])", " ", out)
    out = _sub(r"\\[,;!:>]", " ", out)
    out = _sub(r"\\ ", " ", out)
    out = out.replace("~", " ")
    out = _sub(r"\\left\s*\.", "", out)
    out = _sub(r"\\right\s*\.", "", out)
    out = _sub(r"\\left(?![a-zA-Z])", "", out)
    out = _sub(r"\\right(?![a-zA-Z])", "", out)
    out = _sub(r"\\%", "", out)
    if out != before:
        notes.append("removed layout commands")
    return out


def _read_group(s: str, start: int) -> tuple[str, int] | None:
    """One balanced {...} group starting at `start`, or None when unbalanced."""
    if start >= len(s) or s[start] != "{":
        return None
    depth = 0
    for i in range(start, len(s)):
        # JS reads s[-1] as undefined; Python would wrap to the last character.
        prev = s[i - 1] if i > 0 else ""
        if s[i] == "{" and prev != "\\":
            depth += 1
        elif s[i] == "}" and prev != "\\":
            depth -= 1
            if depth == 0:
                return s[start + 1:i], i + 1
    return None


def _unwrap_transparent(s: str, notes: list[str]) -> str:
    out = s
    changed = False
    for _ in range(5):
        nxt = out
        for cmd in TRANSPARENT_WRAPPERS:
            marker = f"\\{cmd}"
            index = nxt.find(marker)
            while index >= 0:
                after = index + len(marker)
                following = nxt[after] if after < len(nxt) else ""
                if re.match(r"[a-zA-Z]", following):
                    index = nxt.find(marker, after)
                    continue
                group = _read_group(nxt, after)
                if group is None:
                    index = nxt.find(marker, after)
                    continue
                body, end = group
                nxt = nxt[:index] + body + nxt[end:]
                changed = True
                index = nxt.find(marker)
        if nxt == out:
            break
        out = nxt
    if changed:
        notes.append("unwrapped text and font commands")
    return out


_FRAC_HEAD = re.compile(r"^\\(frac|dfrac|tfrac|binom)(?![a-zA-Z])")
_CONTROL_WORD = re.compile(r"^\\[a-zA-Z]+")


def _brace_fraction_arguments(s: str, notes: list[str]) -> str:
    out: list[str] = []
    i = 0
    changed = False
    while i < len(s):
        match = _FRAC_HEAD.match(s[i:])
        if not match:
            out.append(s[i])
            i += 1
            continue
        out.append(f"\\{match.group(1)}")
        i += len(match.group(0))
        for _ in range(2):
            while i < len(s) and s[i] == " ":
                i += 1
            group = _read_group(s, i)
            if group is not None:
                body, end = group
                out.append(f"{{{body}}}")
                i = end
            elif i < len(s):
                # LaTeX shorthand takes exactly one token: \frac12 is one half,
                # not twelve over something. A control sequence is one token.
                command = _CONTROL_WORD.match(s[i:])
                token = command.group(0) if command else s[i]
                out.append(f"{{{token}}}")
                i += len(token)
                changed = True
    if changed:
        notes.append("added braces to fraction arguments")
    return "".join(out)


_EXPONENT = re.compile(r"\^\s*(\d|[a-zA-Z])(?![}\da-zA-Z])")


def _brace_exponents(s: str, notes: list[str]) -> str:
    out = _EXPONENT.sub(lambda m: "^{" + m.group(1) + "}", s)
    if out != s:
        notes.append("added braces to exponents")
    return out


def _balance_braces(s: str, notes: list[str]) -> str:
    depth = 0
    out: list[str] = []
    for i, c in enumerate(s):
        prev = s[i - 1] if i > 0 else ""
        if c == "{" and prev != "\\":
            depth += 1
        if c == "}" and prev != "\\":
            if depth == 0:
                notes.append("dropped an unmatched closing brace")
                continue
            depth -= 1
        out.append(c)
    if depth > 0:
        notes.append(f"closed {depth} unmatched brace{'' if depth == 1 else 's'}")
        out.append("}" * depth)
    return "".join(out)


def _tidy_spacing(s: str) -> str:
    out = _sub(r"\s+", " ", s)
    out = re.sub(r"\s*([+\-=<>])\s*", lambda m: " " + m.group(1) + " ", out)
    out = _sub(r"\s*\^\s*", "^", out)
    out = _sub(r"\s*_\s*", "_", out)
    out = _sub(r"\{\s*-\s*", "{-", out)
    out = _sub(r"\^\s*-\s*", "^-", out)
    out = _sub(r"\{\s+", "{", out)
    out = _sub(r"\s+\}", "}", out)
    out = _sub(r"\s+", " ", out)
    return out.strip()


def _strip_trailing_punctuation(s: str, notes: list[str]) -> str:
    out = _sub(r"[.,;:]+$", "", s).strip()
    if out != s:
        notes.append("removed trailing punctuation")
    return out


def normalize_with_report(raw: str) -> NormalizeReport:
    """Clean OCR-style LaTeX into parseable LaTeX, reporting what changed."""
    notes: list[str] = []
    if not raw or not raw.strip():
        return NormalizeReport("", ["empty result"])

    out = raw
    out = _strip_delimiters(out, notes)
    out = _replace_unicode(out, notes)
    # Balance first: every later pass reads balanced groups.
    out = _balance_braces(out, notes)
    out = _unwrap_transparent(out, notes)
    out = _strip_noise(out, notes)
    out = _brace_fraction_arguments(out, notes)
    out = _brace_exponents(out, notes)
    out = _balance_braces(out, notes)
    out = _strip_trailing_punctuation(out, notes)
    out = _tidy_spacing(out)
    return NormalizeReport(out, notes)


def normalize_latex(raw: str) -> str:
    return normalize_with_report(raw).latex


OUT_OF_SCOPE: list[tuple[re.Pattern[str], str]] = [
    (re.compile(r"\\begin\s*\{"), "matrices and aligned environments"),
    (re.compile(r"\\int|\\oint"), "integrals"),
    (re.compile(r"\\sum|\\prod"), "sums and products"),
    (re.compile(r"\\lim"), "limits"),
    (re.compile(r"\\frac\s*\{\s*d\s*\}\s*\{\s*d"), "derivatives"),
    (re.compile(r"\\infty"), "infinity"),
    (re.compile(r"\\pm|\\mp"), "plus-or-minus"),
]


def detect_out_of_scope(latex: str) -> str | None:
    """Mirror of detectOutOfScope: structures the solver has no rules for."""
    for pattern, label in OUT_OF_SCOPE:
        if pattern.search(latex):
            return label
    return None
